### ISSUE TITLE
Incorrect elevation

### ISSUE THREAD

**Issue by GCNorth** [stamen/terrain-classic#108]
Slide Mountain, NY, is labeled as being 4200 m,  when it should be 1280 m.  It is approximately 4200 ft.

**Comment by almccon** [comment]
Thanks for the bug report, @GCNorth. The elevation data for those peak labels comes from Natural Earth. I don't have time to check right now, but we should look in the Natural Earth data to see if the elevation is correct there.

See also #101 for a similar error. And if the error is present in Natural Earth, we should open an issue there: https://github.com/nvkelso/natural-earth-vector/issues/

**Comment by almccon** [comment]
It looks like this data bug has been fixed in Natural Earth: https://github.com/nvkelso/natural-earth-vector/issues/169. Currently the data for Terrain hasn't been updated in years, but when we do finally update the data, we can pull from a newer version of Natural Earth that doesn't have this error.
