### ISSUE TITLE
water stroke is too thick at low zooms

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#13]
![screen shot 2015-08-24 at 3 16 51 pm](https://cloud.githubusercontent.com/assets/1212178/9453979/3e8c1788-4a73-11e5-87e0-73a712c4c9ca.png)

Probably not necessary at low zooms. I recall that we depend on water outlines at high zooms, but I don't remember exactly why.

**Comment by clhenrick** [comment]
@almccon could you clarify this?

**Comment by almccon** [comment]
The water outlines are the same color as the water, so they're hard to spot, but at this zoom they are so fat that they spill onto the land. Denmark, for example, looks almost totally flooded.

**Comment by clhenrick** [comment]
Ah, okay that should be an easy fix (fingers crossed) thanks for clarifying.

**Comment by clhenrick** [comment]
@almccon seems like the culprit could be here: https://github.com/stamen/terrain-classic/blob/master/map.mss#L84-L92

However I'm not able to replicate this issue. When i change the color of the stroke it seems like it's already fairly thin. I do think the coastline generalization should change though. For example we should probably use the `ne_50m_ocean` at lower zooms for the coastline rather than the `ne_10m_ocean` which looks a little too detailed.

this is zoom level 4:
![screen shot 2015-09-01 at 4 32 16 pm](https://cloud.githubusercontent.com/assets/161748/9615578/112b0c40-50c7-11e5-963b-af472f9fa4a8.png)

**Comment by almccon** [comment]
Yes, maybe it is think, but even with those thin black lines, they still wash out the land when they're the same color as water. Check out how wet Finland looks at that zoom:
![screen shot 2015-09-01 at 4 40 05 pm](https://cloud.githubusercontent.com/assets/1212178/9619807/691f449c-50c8-11e5-9381-9e2ee6fab025.png)

But it's true that the problem isn't that bad at zoom 4. Zoom 3 is worse. Maybe we need to remove the lines entirely at zoom 0 through 4. Shouldn't have any unexpected consequences, I hope.

**Comment by clhenrick** [comment]
@almccon I feel that leaving out the stroke for water polygons at low zooms would be fine. 

Alternatively we could play with using the  `ne_50m_ocean` layer which has a more generalized coastline and/or making the coastline a darker stroke.

**Comment by clhenrick** [comment]
@almccon changing the map background color to water for low zooms and using the `ne_50m_ocean` layer for the coastline seems to resolve this:

![screen shot 2015-09-02 at 3 40 34 pm](https://cloud.githubusercontent.com/assets/161748/9642235/ffbd9fc8-5188-11e5-8f30-ffce2a0d203b.png)

**Comment by almccon** [comment]
Works for me. :ocean:
