### ISSUE TITLE
order Aries labels by population and scalerank

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#34]
See #26 for more discussion. 

In this screenshot, Mexico City should show up. http://localhost:8080/flat/#8/19.329/-98.871

![screen shot 2015-09-21 at 2 45 43 pm](https://cloud.githubusercontent.com/assets/1212178/10006062/9f7ff570-606f-11e5-8e40-15e08e63c38b.png)

**Comment by clhenrick** [comment]
I wonder if the airport icon has anything to do with Mexico City not showing? I assume the layer order determines priority of labeling as well, but if that's so then the airport icon wouldn't be an issue as the city labels are stacked on top of the airports.

**Comment by clhenrick** [comment]
@almccon the same issue is happening in Seattle, believe it has to do with the highway shield icons. This leads me to believe the issue is a label conflict with layers that are using `shield-` vs `text-` properties and TileMill is giving preference to `shield-` layers. 

For example if I turn off the `#highway_shield` layer then the label for Seattle renders at zoom 12:

![screen shot 2015-10-26 at 2 49 15 pm](https://cloud.githubusercontent.com/assets/161748/10739121/0db58090-7bf1-11e5-8263-72dde50a5564.png)

![screen shot 2015-10-26 at 2 49 00 pm](https://cloud.githubusercontent.com/assets/161748/10739122/0dc047dc-7bf1-11e5-9d06-086b4eb2619f.png)

Same thing happens for Mexico City with the airport icon at lower zooms:

![screen shot 2015-10-26 at 3 00 21 pm](https://cloud.githubusercontent.com/assets/161748/10739363/5964e52a-7bf2-11e5-877c-7a9d023b5bf9.png)

![screen shot 2015-10-26 at 2 59 54 pm](https://cloud.githubusercontent.com/assets/161748/10739362/5962c498-7bf2-11e5-8720-b5c507b6bcb0.png)

Any ideas what a solution to this might be?

**Comment by clhenrick** [comment]
Also posted this in #42, but the following changes in 2804c4d seems to help:

- Not rendering airport icons until zoom 12 to give city labels a better chance of rendering. This seems to help with Mexico City.
- Setting the text-wrap-width property helps keep the text in a smaller area, giving it a better chance of rendering.
- Using population to determine what labels get rendered at zooms 9 - 12 which helps with areas outside of the U.S

![screen shot 2015-10-26 at 4 18 49 pm](https://cloud.githubusercontent.com/assets/161748/10741294/5ab4467c-7bfd-11e5-9f3b-96466bca9ffc.png)
![screen shot 2015-10-26 at 4 19 05 pm](https://cloud.githubusercontent.com/assets/161748/10741299/5cbe5282-7bfd-11e5-9786-6344cf39904c.png)
![screen shot 2015-10-26 at 4 19 17 pm](https://cloud.githubusercontent.com/assets/161748/10741302/5f1117d6-7bfd-11e5-8fcd-cf8a1e3e4230.png)

**Comment by almccon** [comment]
New sorting in the Aries query keeps Mexico City on top. There's only one zoom (11) where the sorting fails. Not sure why. But I'm calling this done.
![screen shot 2015-11-04 at 5 01 10 pm](https://github-cloud.s3.amazonaws.com/assets%2F1212178%2F10957079%2Fe3470596-8315-11e5-8a74-2c26fd4786a4.png)

See also #42.
