### ISSUE TITLE
Small osm_admin boundaries should not render at low zooms

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#39]
When looking at Seattle I noticed an odd artifact at `#10/47.1159/-122.0821`. On zooming in it turns out to be a small tribal administrative boundary. We should probably add a query that prevents small admin areas from rendering at low zooms so we don't end up with black specs on the map.

Notice the speck below Prairie Ridge
![screen shot 2015-10-22 at 5 19 32 pm](https://cloud.githubusercontent.com/assets/161748/10678557/31cf8a10-78e1-11e5-8e10-4f6c0f51447b.png)

![screen shot 2015-10-22 at 5 16 04 pm](https://cloud.githubusercontent.com/assets/161748/10678551/2c04073c-78e1-11e5-84fe-8a21d6da20df.png)

Identified in QGIS:
![screen shot 2015-10-22 at 5 18 29 pm](https://cloud.githubusercontent.com/assets/161748/10678553/2f641d9a-78e1-11e5-9a39-8ec0f3321925.png)

**Comment by almccon** [comment]
Good point. Indian Reservations in OSM are extremely poorly mapped (a project for another day), but we should try to handle them correctly in case more get added. Is it black because that's the correct style for admin boundaries at that zoom, or is it black because we failed to completely apply a style to that feature?

**Comment by clhenrick** [comment]
Not sure, feel like I've noticed this pattern (dashed black lines) elsewhere so will look more closely for where it is or is not coming from.

**Comment by clhenrick** [comment]
Looks like we are switching from NE admin boundaries to OSM boundaries at zoom 10 but with nothing to filter out small administrative areas at high zooms. Would calculating area for a filter make sense as a way to resolve this? Or perhaps doing a `ILIKE '%reservation%'` on `name`?

**Comment by clhenrick** [comment]
It appears that Indian Reservations fall within the `admin_level = 4` query in the `.yaml` files. Perhaps calculating an area field in the `osm_admin` table is the best bet. That way we can filter out really small admin areas at lower zoom levels but still show them at higher zooms.

**Comment by clhenrick** [comment]
Fixed via commit 1403967

**Comment by almccon** [comment]
Looks like this requires we run `osm_admin_area.sql` during database setup? I'll add that to the Makefile

**Comment by clhenrick** [comment]
Ah yeah it does, I had assumed the make file executes whatever lives in
sql/functions/ when creating a db.


-Chris L Henrick

http://chrishenrick.com
https://clhenrick.github.io
https://chenrickmfadt.wordpress.com/

*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by almccon** [comment]
There are a ton of `admin_level = 4` boundaries in Switzerland, and it still looks messy. Dotted-line boundaries are a pain, because when you've got overlapping borders the dotted lines get out of sync, so it ends up looking almost solid sometimes.
![screen shot 2015-10-26 at 6 17 37 pm](https://cloud.githubusercontent.com/assets/1212178/10747051/198f7cb4-7c0e-11e5-9da2-154b688afc02.png)

I'm going to tone them down some more, at least.

**Comment by clhenrick** [comment]
Ah, good catch. I agree using the lighter boundary style would be an improvement for these.
