### ISSUE TITLE
show city names at higher zooms

### ISSUE THREAD

**Issue by almccon** [stamen/terrain-classic#42]
Currently the city names disappear at z11, leaving the map looking pretty empty until street names starting to trickle in. OG Terrain keeps city names on the map until z16! I kind of like it.
![screen shot 2015-10-22 at 6 20 17 pm](https://cloud.githubusercontent.com/assets/1212178/10682383/f54bc712-78e9-11e5-943d-eead776bac49.png)

**Comment by clhenrick** [comment]
I'm wondering if this has something to do with Mapnik and/or Tessera as there's nothing I can see in the CartoCSS or YML files telling Mapnik to not render place / city labels at higher zooms. 

Is there a way we can tell Mapnik to prioritize certain labels above others so that they will always render? I'm thinking at the higher zooms the city labels might be conflicting with labels for roads, water bodies, highway shields, etc.

I've been running into an issue when running Tessera where shields are rendering but not their labels. In the screenshots below "EastGate" and highway shield labels should be rendering in the side-by-side Tessara view:

![screen shot 2015-10-24 at 4 58 49 pm](https://cloud.githubusercontent.com/assets/161748/10712749/fde7f69c-7a70-11e5-80aa-4bf38b08d79e.png)

![screen shot 2015-10-24 at 4 58 26 pm](https://cloud.githubusercontent.com/assets/161748/10712750/fde825d6-7a70-11e5-82b2-1d324ada941c.png)

Any thoughts about this @mojodna?

**Comment by almccon** [comment]
I suspect it's a problem with the yml files getting out of sync. The side-by-side viewer uses the stacked layers, but TileMill would only use `terrain-classic.yml`. So I'm guessing that the code for the shields in `terrain-classic.yml` is different from the code in `terrain-classic-labels.yml`?

**Comment by clhenrick** [comment]
I looked at both the terrain-classic.yml and terrain-classic-labels.yml
files and they seem pretty similar, though maybe I'm overlooking something.
Could it be the layer order is different when the yml files are sandwiched
with tessera?

On Saturday, October 24, 2015, Alan McConchie <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> I suspect it's a problem with the yml files getting out of sync. The
> side-by-side viewer uses the stacked layers, but TileMill would only use
> terrain-classic.yml. So I'm guessing that the code for the shields in
> terrain-classic.yml is different from the code in
> terrain-classic-labels.yml?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/terrain-classic/issues/42#issuecomment-150873576>
> .
>


-- 

-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by clhenrick** [comment]
So I altered the YML and labels.mss files and think it's helping. 

- duplicated the aries-places layer for higher zooms, and using plain old `text-` rather than `shield-` properties which seems to help the labels display at higher zooms.
- Also setting the `text-wrap-width` property helps keep the text in a smaller area, giving it a better chance of rendering.
- Using population to determine what labels get rendered at zooms 9 - 12 which helps with areas outside of the U.S.

However I'm still having difficulty getting the labels to render past zoom 14 and am thinking this is due to street, water and parks labels crowding out the area where text can be rendered. Turning off street labels for example enables city labels to be rendered at higher zoom levels.

![screen shot 2015-10-26 at 4 02 06 pm](https://cloud.githubusercontent.com/assets/161748/10741116/718e1b58-7bfc-11e5-9398-bc64dba0d8a1.png)
![screen shot 2015-10-26 at 4 01 51 pm](https://cloud.githubusercontent.com/assets/161748/10741115/718e2cec-7bfc-11e5-801b-b0aa31fcb51e.png)

**Comment by almccon** [comment]
I've got labels rendering up to z16 now, by re-ordering the yml files so the aries labels are drawn before any other labels.
![screen shot 2015-11-04 at 5 00 09 pm](https://github-cloud.s3.amazonaws.com/assets%2F1212178%2F10957044%2F9b13f39c-8315-11e5-80f9-04e96a8fb2f1.png)

They also get drawn before airports, too, so we still see Mexico City at lower zooms:
![screen shot 2015-11-04 at 5 01 10 pm](https://github-cloud.s3.amazonaws.com/assets%2F1212178%2F10957058%2Fb6e2fcc6-8315-11e5-8ced-6ad6bba2073b.png)

**Comment by clhenrick** [comment]
awesome!


-Chris L Henrick

http://chrishenrick.com
https://clhenrick.github.io
https://chenrickmfadt.wordpress.com/

*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells
