### ISSUE TITLE
OSM landcover oddities

### ISSUE THREAD

**Issue by clhenrick** [stamen/terrain-classic#54]
![screen shot 2015-05-19 at 5 11 08 pm](https://cloud.githubusercontent.com/assets/161748/16499417/41abc97c-3eb5-11e6-93bc-bdb8b6d3cbd0.png)

@almccon can you give me details so I can attempt to reproduce?

**Comment by almccon** [comment]
This is what happens if you try to define the colors in CartoCSS instead of in a VRT, and try to apply `raster-scaling: gaussian`. Unfortunately I don't think I have the CartoCSS that generated this. (This was back in mid-May 2015)

It might be moot, because @mojodna might have another path for getting the landcover into the database, so don't worry about this one yet until he says we need to worry.

**Comment by mojodna** [comment]
Yup, this is moot. We're still using a VRT, but the TIFF itself is being read from S3.
